#!/usr/bin/env python3
"""A03 closing checks for the Phase A integration (run AFTER the ledger is closed).

Validates:
  1. artifact existence;
  2. the fixture provenance manifest: entry counts, destination hashes on disk,
     containment in the fixture root, copy stability, synthetic labelling,
     generator hash == the capture tool on disk;
  3. the independent source-vs-copy cross-check transcript reports PASS;
  4. the capture tool's own --check mode returns 0;
  5. no database/credential/archive fixture and no examination-material canary;
  6. the staged suite transcript reports 29 passed with no failures, and the
     ledger exit codes agree with the recorded failures;
  7. the leak check shows no new __pycache__ in protected roots, and the
     attribution transcript (regenerated by tools/a03_attribution.py) names both
     basetemps and accounts for the out-of-allowlist writes;
  8. ledger: 27 tasks, A03 staged_pass, 7 gates closed, no merged_pass, A03 fields;
  9. sha256 manifest of both Phase A roots (excluding this transcript).

Writes (and prints) the transcript to
  docs/integration/execution/evidence/A03/final_checks.txt  (override with --out)
and exits 0 (PASS) or 1 (FAIL).

Phase A tool (integration-staging/tools/). Stdlib only; nothing original is modified.
"""
from __future__ import annotations

import argparse
import contextlib
import hashlib
import importlib.util
import io
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.dont_write_bytecode = True

WS = Path(__file__).resolve().parents[2]
EXEC = WS / "docs" / "integration" / "execution"
EV = EXEC / "evidence" / "A03"
STAGING = WS / "integration-staging"
FIXTURES = STAGING / "fixtures"
ROOTS = [STAGING, EXEC]

EXPECTED_TASK_IDS = ["A%02d" % i for i in range(16)] + ["B%02d" % i for i in range(11)]
DENY_SUFFIXES = (".db", ".sqlite", ".sqlite3", ".duckdb", ".parquet", ".pdf", ".mp3", ".wav",
                 ".pem", ".key", ".zip", ".tar", ".gz")
CANARY = "Express 3y"
CAPTURE_TOOL = STAGING / "tools" / "a03_capture_fixtures.py"

checks: list[tuple[str, bool, str]] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    checks.append((name, bool(ok), detail))


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def load_json(p: Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


def rel(p: Path) -> str:
    return p.relative_to(WS).as_posix()


def is_within(child: Path, parent: Path) -> bool:
    import os
    c, p = os.path.normcase(os.path.realpath(child)), os.path.normcase(os.path.realpath(parent))
    return c == p or c.startswith(p + os.sep)


def load_capture_tool():
    spec = importlib.util.spec_from_file_location("a03_capture_fixtures_probe", CAPTURE_TOOL)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(EV / "final_checks.txt"))
    args = ap.parse_args()
    out_path = Path(args.out)
    out_path = (out_path if out_path.is_absolute() else WS / out_path).resolve()

    lines: list[str] = []

    def emit(s: str = "") -> None:
        lines.append(s)

    emit("=== A03 final checks (runner: integration-staging/tools/a03_final_checks.py) ===")
    emit(f"generated_at_local: {datetime.now().astimezone().isoformat(timespec='seconds')}")
    emit(f"generated_at_utc:   {datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    emit(f"cwd: {Path.cwd()}")
    emit()

    # ---- 1. artifact existence -------------------------------------------------
    emit("--- 1. artifact existence ---")
    required = [
        "integration-staging/fixtures/PROVENANCE.json",
        "integration-staging/fixtures/PROVENANCE.md",
        "integration-staging/fixtures/README.md",
        "integration-staging/fixtures/copied/ielts/indexes-current.json",
        "integration-staging/fixtures/copied/ielts/manifests-current.json",
        "integration-staging/fixtures/copied/ielts/pdf-provenance.json",
        "integration-staging/fixtures/copied/ielts/printed-pages.json",
        "integration-staging/fixtures/copied/edexcel/subjects-source.json",
        "integration-staging/fixtures/copied/toefl/ddy-index.json",
        "integration-staging/fixtures/synthetic/ielts/questions-synthetic.json",
        "integration-staging/fixtures/synthetic/cie/cie-index-synthetic.json",
        "integration-staging/fixtures/synthetic/edexcel/index-synthetic.json",
        "integration-staging/tools/a03_capture_fixtures.py",
        "integration-staging/tools/a03_attribution.py",
        "integration-staging/tools/a03_final_checks.py",
        "integration-staging/tests/test_fixture_provenance.py",
        "integration-staging/runtime/ledger-patches/A03_close.json",
        "docs/integration/execution/A03_REPORT.md",
        "docs/integration/execution/execution-ledger.json",
        "docs/integration/execution/evidence/A03/fixture_capture_stdout.txt",
        "docs/integration/execution/evidence/A03/fixture_hash_crosscheck.txt",
        "docs/integration/execution/evidence/A03/pytest_run_stdout.txt",
        "docs/integration/execution/evidence/A03/leak_check_after_capture.txt",
        "docs/integration/execution/evidence/A03/owner_activity_attribution.txt",
        "docs/integration/execution/evidence/A03/attribution_generator_stdout.txt",
    ]
    missing_files = [r for r in required if not (WS / r).is_file()]
    emit(f"missing={missing_files}")
    check("artifacts.all_present", not missing_files)

    # ---- 2. provenance manifest --------------------------------------------------
    emit()
    emit("--- 2. fixture provenance manifest ---")
    manifest = {}
    try:
        manifest = load_json(FIXTURES / "PROVENANCE.json")
        entries = manifest["entries"]
        copied = [e for e in entries if e["kind"] == "copied_snapshot"]
        synthetic = [e for e in entries if e["kind"] == "synthetic"]
        emit(f"schema={manifest['schema']} entries={len(entries)} copied={len(copied)} synthetic={len(synthetic)}")
        emit(f"summary={json.dumps(manifest['summary'], sort_keys=True)}")
        emit(f"deferred_sources={len(manifest['deferred_sources'])}")
        check("manifest.counts",
              len(copied) == 6 and len(synthetic) == 3
              and manifest["summary"]["copied"] == 6 and manifest["summary"]["synthetic"] == 3)
        check("manifest.generator_hash", manifest["generator_sha256"] == sha256_file(CAPTURE_TOOL))

        bad_hash, bad_place, bad_stable, bad_label = [], [], [], []
        for e in entries:
            dst = WS / e["destination_path"]
            if not is_within(dst, FIXTURES):
                bad_place.append(e["fixture_id"])
            if not dst.is_file():
                bad_hash.append(f"{e['fixture_id']}: missing")
                continue
            if sha256_file(dst) != e["destination_sha256"]:
                bad_hash.append(f"{e['fixture_id']}: hash")
            if e["kind"] == "copied_snapshot":
                if not (e["status"] == "copied" and e["stable"] is True
                        and e["content_matches"] is True
                        and e["source_sha256_before"] == e["source_sha256_after"]
                        == e["destination_sha256"]):
                    bad_stable.append(e["fixture_id"])
            else:
                if e["label"] != "synthetic_fixture" or e["synthetic_marker_present"] is not True \
                        or e["source_path"] is not None:
                    bad_label.append(e["fixture_id"])
        emit(f"hash_problems={bad_hash} outside_fixture_root={bad_place}")
        emit(f"unstable_copies={bad_stable} mislabelled_synthetic={bad_label}")
        check("manifest.destination_hashes_match", not bad_hash)
        check("manifest.all_inside_fixture_root", not bad_place)
        check("manifest.copies_stable", not bad_stable)
        check("manifest.synthetic_labelled", not bad_label)
        check("manifest.provenance_fields",
              all(all(k in e for k in ("scope", "destination_path", "label")) for e in entries))

        cie = "cie-index-batch-2026-10-01/9709/2024-Jun-11/cie-index.json"
        deferred = {d["source"]: d for d in manifest["deferred_sources"]}
        emit(f"cie_index_status={deferred.get(cie, {}).get('status')}")
        check("manifest.exam_material_deferred",
              cie in deferred and deferred[cie]["status"] == "deferred_examination_material"
              and cie not in {e.get("source_path") for e in copied})
    except Exception as e:  # noqa: BLE001
        check("manifest.load_and_validate", False, f"exception={e!r}")

    # ---- 3. independent cross-check transcript -----------------------------------
    emit()
    emit("--- 3. independent source-vs-copy cross-check ---")
    try:
        text = (EV / "fixture_hash_crosscheck.txt").read_text(encoding="utf-8")
        emit(f"MATCH lines={text.count('MATCH  ')}")
        check("crosscheck.independent_pass",
              "independent_crosscheck: PASS" in text and text.count("MATCH  ") == 6)
    except Exception as e:  # noqa: BLE001
        check("crosscheck.independent_pass", False, f"exception={e!r}")

    # ---- 4. capture tool --check mode ---------------------------------------------
    emit()
    emit("--- 4. capture tool --check (re-verify without copying) ---")
    try:
        module = load_capture_tool()
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = module.run_check()
        emit(f"tool --check exit={rc}")
        emit(buf.getvalue().strip()[:400])
        check("capture_tool.check_mode_zero", rc == 0, f"rc={rc}")
    except Exception as e:  # noqa: BLE001
        check("capture_tool.check_mode_zero", False, f"exception={e!r}")

    # ---- 5. deny list and canary ----------------------------------------------------
    emit()
    emit("--- 5. no forbidden fixture type; no examination-material canary ---")
    try:
        offenders, canaries = [], []
        for p in sorted(FIXTURES.rglob("*")):
            if not p.is_file():
                continue
            if p.name.lower().endswith(DENY_SUFFIXES):
                offenders.append(rel(p))
            if CANARY in p.read_text(encoding="utf-8", errors="replace"):
                canaries.append(rel(p))
        emit(f"deny_list_hits={offenders} canary_hits={canaries}")
        check("fixtures.no_denied_type", not offenders)
        check("fixtures.no_exam_material_canary", not canaries)
    except Exception as e:  # noqa: BLE001
        check("fixtures.no_denied_type", False, f"exception={e!r}")

    # ---- 6. pytest transcript + ledger exit codes ----------------------------------
    emit()
    emit("--- 6. staged suite transcript and ledger exit codes ---")
    try:
        text = (EV / "pytest_run_stdout.txt").read_text(encoding="utf-8")
        ok29 = "29 passed" in text and "failed" not in text.lower()
        emit(f"'29 passed'={ok29}")
        check("pytest.transcript_29_passed", ok29)
    except Exception as e:  # noqa: BLE001
        check("pytest.transcript_29_passed", False, f"exception={e!r}")

    try:
        led = load_json(EXEC / "execution-ledger.json")
        by_id = {t.get("task_id"): t for t in led.get("tasks", [])}
        a03 = by_id.get("A03", {})
        codes = a03.get("exit_codes", [])
        nonzero = [c for c in codes if c not in (0, None)]
        failures = a03.get("failures") or []
        emit(f"A03 exit_codes={codes} nonzero={nonzero} failures={len(failures)}")
        check("pytest.ledger_exit_codes_consistent",
              bool(codes) and len(nonzero) == len(failures) and set(nonzero) <= {1},
              f"codes={codes} nonzero={nonzero} failures={len(failures)}")
    except Exception as e:  # noqa: BLE001
        check("pytest.ledger_exit_codes_consistent", False, f"exception={e!r}")

    # ---- 7. leak check + attribution -----------------------------------------------
    emit()
    emit("--- 7. leak check and owner-activity attribution ---")
    try:
        leak = (EV / "leak_check_after_capture.txt").read_text(encoding="utf-8")
        attr = (EV / "owner_activity_attribution.txt").read_text(encoding="utf-8")
        gen_stdout = (EV / "attribution_generator_stdout.txt").read_text(encoding="utf-8")
        zero_counts = leak.count("(count: 0)")
        emit(f"leak zero-count lines={zero_counts} (expected 1: new __pycache__ in protected roots)")
        emit(f"attribution mentions owner basetemp={'pytest-of-weo' in attr} "
             f"and executor basetemp={'integration-staging/runtime/pytest-temp' in attr}")
        emit(f"attribution generator declared={'a03_attribution.py' in attr} "
             f"generator stdout 'wrote'={'wrote ' in gen_stdout}")
        check("leak_check.no_new_pycache_in_protected_roots", "(count: 0)" in leak, )
        check("attribution.executor_basetemp_named",
              "integration-staging/runtime/pytest-temp" in attr
              and "inside the allowlist: True" in attr)
        check("attribution.owner_basetemp_named", "pytest-of-weo" in attr)
        check("attribution.generated_by_tool",
              "a03_attribution.py" in attr and "wrote " in gen_stdout
              and "executor_basetemp=integration-staging/runtime/pytest-temp" in gen_stdout)
        check("attribution.conclusion_present",
              "Executor writes in this window: integration-staging/** and "
              "docs/integration/execution/** only." in attr)
    except Exception as e:  # noqa: BLE001
        check("attribution.executor_basetemp_named", False, f"exception={e!r}")

    # ---- 8. ledger state -------------------------------------------------------------
    emit()
    emit("--- 8. ledger state ---")
    try:
        tasks = led.get("tasks", [])
        ids = [t.get("task_id") for t in tasks]
        gates = led.get("gates", {})
        open_gates = [g for g, v in gates.items() if v.get("open")]
        all_statuses: dict[str, int] = {}
        for t in tasks:
            all_statuses[t["status"]] = all_statuses.get(t["status"], 0) + 1
        expected_roots = [(WS / "integration-staging").as_posix(),
                          (WS / "docs" / "integration" / "execution").as_posix()]
        emit(f"task_count={len(ids)} unique={len(set(ids))} statuses={json.dumps(all_statuses, sort_keys=True)}")
        emit(f"A03_status={a03.get('status')} gates={len(gates)} open={open_gates}")
        check("ledger.count_unique_27",
              len(ids) == 27 and len(set(ids)) == 27
              and not [t for t in EXPECTED_TASK_IDS if t not in ids]
              and not [t for t in ids if t not in EXPECTED_TASK_IDS])
        check("ledger.a03_staged_pass", a03.get("status") == "staged_pass", f"A03={a03.get('status')}")
        check("ledger.no_merged_pass", "merged_pass" not in all_statuses)
        check("ledger.gates_closed", len(gates) == 7 and not open_gates, f"open={open_gates}")
        check("ledger.a03_write_roots",
              a03.get("allowed_write_roots") == expected_roots
              and led.get("allowed_write_roots") == expected_roots)
        check("ledger.a03_record_fields",
              bool(a03.get("evidence_paths")) and bool(a03.get("input_hashes"))
              and bool(a03.get("commands")) and bool(a03.get("changed_files"))
              and bool(a03.get("test_results")) and bool(a03.get("remaining_gaps"))
              and (a03.get("next_action") or "").strip() != "")
    except Exception as e:  # noqa: BLE001
        check("ledger.load_and_validate", False, f"exception={e!r}")

    # ---- 9. inventory + sha256 manifest ------------------------------------------------
    emit()
    emit("--- 9. artifact inventory + sha256 manifest (excluding this transcript) ---")
    all_files: list[Path] = []
    for root in ROOTS:
        for p in sorted(root.rglob("*")):
            if p.is_file() and p.resolve() != out_path:
                all_files.append(p)
    for p in all_files:
        emit(rel(p))
    emit()
    emit("--- manifest ---")
    for p in all_files:
        emit(f"{sha256_file(p)} *{rel(p)}")

    # ---- verdict -------------------------------------------------------------------------
    emit()
    emit("--- 10. verdict ---")
    failed = [(n, d) for n, ok, d in checks if not ok]
    for n, ok, d in checks:
        emit(f"{n}: {'PASS' if ok else 'FAIL'}{(' (' + d + ')') if d and not ok else ''}")
    ok_all = not failed
    emit(f"A03_FINAL_CHECKS_JSON: {'PASS' if ok_all else 'FAIL'}")
    emit(f"FINAL_CHECKS: {'PASS' if ok_all else 'FAIL'}")

    text = "\n".join(lines) + "\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8", newline="\n")
    sys.stdout.write(text)
    return 0 if ok_all else 1


if __name__ == "__main__":
    sys.exit(main())
