"""Legacy compatibility decisions (plan 5.5, packet A12 - proposal).

The per-route record for all 71 baseline routes lives in `registry.json`,
generated by `integration-staging/tools/a12_build_registry.py`. This module is
the read API: it loads and validates the registry lazily (so importing the
`legacy` package never depends on the file existing) and every consumer -
tests, the worksheet builder, the probe - goes through it, so there is exactly
one spelling of a route id and one mechanism vocabulary.

Nothing here reads the original tree, the network, a database or a service.
"""
from __future__ import annotations

import hashlib
import json
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

REGISTRY_PATH = Path(__file__).resolve().with_name("registry.json")

SCHEMA = "examdata.integration.legacy_registry/1"

#: Status vocabulary fixed by plan 5.5; no other value may appear.
ALLOWED_STATUSES: tuple[str, ...] = (
    "not_started",
    "fixture_ready",
    "staged_pass",
    "merged_pass",
    "deferred_active_owner",
    "blocked",
    "not_applicable_with_reason",
)

#: Mechanism vocabulary fixed by the A12 compatibility design.
MECHANISMS: tuple[str, ...] = (
    "add_v2_adapter_keep_legacy_defaults",
    "keep_legacy_only",
    "keep_legacy_namespace",
    "bridge_node_cli_keep_legacy_payload",
    "deferred_active_owner",
)


def slug_path(path: str) -> str:
    """`/api/v1/ielts/v2/asset/{asset_id}` -> `api_v1_ielts_v2_asset_asset_id`."""
    text = path.strip("/")
    text = text.replace("{", "").replace("}", "")
    text = re.sub(r"[^0-9A-Za-z]+", "_", text)
    return text.strip("_")


def row_id(method: str, path: str) -> str:
    """The stable worksheet/test id of one route: `GET__health`."""
    return f"{method.upper()}__{slug_path(path)}"


@lru_cache(maxsize=1)
def registry() -> dict[str, Any]:
    """Load + validate the registry once per process."""
    raw = REGISTRY_PATH.read_bytes()
    document = json.loads(raw.decode("utf-8"))
    if document.get("schema") != SCHEMA:
        raise RuntimeError(f"legacy registry schema {document.get('schema')!r} != {SCHEMA!r}")
    rows = document.get("rows")
    if not isinstance(rows, list) or not rows:
        raise RuntimeError("legacy registry carries no rows")
    seen: set[str] = set()
    for row in rows:
        rid = row.get("row_id")
        if not rid or rid in seen:
            raise RuntimeError(f"duplicate or missing row_id {rid!r}")
        seen.add(rid)
        if row.get("status") not in ALLOWED_STATUSES:
            raise RuntimeError(f"row {rid} carries status {row.get('status')!r}")
        if row.get("mechanism") not in MECHANISMS:
            raise RuntimeError(f"row {rid} carries mechanism {row.get('mechanism')!r}")
    document["_sha256"] = hashlib.sha256(raw).hexdigest()
    return document


def registry_sha256() -> str:
    registry()
    return registry()["_sha256"]


def rows() -> list[dict[str, Any]]:
    return registry()["rows"]


def baseline_count() -> int:
    return len(rows())


def row_by_id(rid: str) -> dict[str, Any]:
    for row in rows():
        if row["row_id"] == rid:
            return row
    raise KeyError(rid)


def row_for(method: str, path: str) -> dict[str, Any]:
    return row_by_id(row_id(method, path))


def deferred_rows() -> list[dict[str, Any]]:
    return [row for row in rows() if row["mechanism"] == "deferred_active_owner"]


def mechanism_counts() -> dict[str, int]:
    counts = {name: 0 for name in MECHANISMS}
    for row in rows():
        counts[row["mechanism"]] += 1
    return counts


def status_counts() -> dict[str, int]:
    counts = {name: 0 for name in ALLOWED_STATUSES}
    for row in rows():
        counts[row["status"]] += 1
    return {name: n for name, n in counts.items() if n}


def coverage_summary() -> dict[str, Any]:
    coverage: dict[str, int] = {}
    for row in rows():
        key = row.get("coverage_kind") or "none"
        coverage[key] = coverage.get(key, 0) + 1
    return {
        "baseline_rows": baseline_count(),
        "by_mechanism": mechanism_counts(),
        "by_status": status_counts(),
        "by_coverage_kind": coverage,
        "deferred_rows": [row["row_id"] for row in deferred_rows()],
    }


__all__ = [
    "ALLOWED_STATUSES",
    "MECHANISMS",
    "REGISTRY_PATH",
    "SCHEMA",
    "baseline_count",
    "coverage_summary",
    "deferred_rows",
    "mechanism_counts",
    "registry",
    "registry_sha256",
    "row_by_id",
    "row_for",
    "row_id",
    "rows",
    "slug_path",
    "status_counts",
]
