import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveSubject,subjectMatches,normalizePaper,groupPapers } from '../search.mjs';
const subjects = [{code:'0580',title:'Mathematics',qualification:'IGCSE'},{code:'9709',title:'Mathematics',qualification:'A Level'},{code:'9231',title:'Further Mathematics',qualification:'A Level'},{code:'0455',title:'Economics',qualification:'IGCSE'}];
test('code with a Chinese name and full-width digits is exact',()=>assert.equal(resolveSubject(subjects,'数学 ９７０９').code,'9709'));
test('three-digit numeric input preserves leading-zero syllabus codes',()=>assert.equal(resolveSubject(subjects,'580').code,'0580'));
test('math defaults to 9709 while explicit IGCSE stays selectable',()=>{assert.equal(resolveSubject(subjects,'数学').code,'9709');assert.equal(resolveSubject(subjects,'maths').code,'9709');assert.equal(resolveSubject(subjects,'mathematics igcse').code,'0580');});
test('qualification resolves a duplicate subject title',()=>assert.equal(resolveSubject(subjects,'mathematics igcse').code,'0580'));
test('name and code pair resolves exact code, not all named subjects',()=>assert.deepEqual(subjectMatches(subjects,'Mathematics · 9709').map(s=>s.code),['9709']));
test('unknown but valid syllabus codes can query live without catalog membership',()=>assert.equal(resolveSubject(subjects,'9868').code,'9868'));
test('partial number cannot match arbitrary syllabus codes',()=>assert.equal(resolveSubject(subjects,'97').code,null));
test('paper prefixes and zero padding normalize consistently',()=>{assert.equal(normalizePaper('Paper 11'),'11');assert.equal(normalizePaper('P1'),'01');assert.equal(normalizePaper('卷 １'),'01');assert.notEqual(normalizePaper('1'),normalizePaper('11'));});
test('Edexcel variant and Chinese subject alias normalize',()=>{assert.equal(normalizePaper('WEC11/01','edexcel'),'wec11-01');assert.equal(resolveSubject([{code:'ial18-economics',title:'Economics (2018)'}],'经济学','edexcel').code,'ial18-economics');});
test('paper and mark scheme pair only with a complete matching identity',()=>{const base={board:'cie',code:'9709',year:2024,season:'Jun',paper:'11'};const groups=groupPapers([{...base,url:'https://test/qp',type:'question_paper'},{...base,url:'https://test/ms',type:'mark_scheme'},{...base,paper:'12',url:'https://test/other'},{...base,paper:null,url:'https://test/unknown'}]);assert.equal(groups.length,3);assert.equal(groups[0].documents.length,2);});
