// ielts-api/tests/ielts-pdf-extract.test.mjs
// S06 acceptance tests for the PDF extraction adapter (pdf-adapter.mjs) and the
// import tool (tools/import-pdf.mjs).
//
// Unit tests are fully offline. The gold-fixture integration tests run the real
// extractor (examdata venv python + PyMuPDF) against the local source PDFs and are
// skipped when the python or a PDF is absent. Fixture expectations were hand-written
// from independent S06 probes (rawdict bboxes / rapidocr / ink row-bands) and are
// never generated by the parser under test.
//
// Run: node --test ielts-api/tests/ielts-pdf-extract.test.mjs

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  extractPdf,
  validateExtractDoc,
  parsePagesSpec,
  normalizePagesSpec,
  sha256FileHex,
  resolvePython,
  PdfAdapterError,
  __internals,
} from "../pdf-adapter.mjs";
import { importPdf } from "../tools/import-pdf.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const API = path.resolve(HERE, "..");
const REPO = path.resolve(API, "..");
const DOWNLOADS = path.join(REPO, "tmp_audit_ielts", "downloads");
const FIXTURES = path.join(HERE, "fixtures", "pdf-expected");
const TEST_DATA = path.join(REPO, "ielts-data", "test-s06");
const TMP_OUT = path.join(TEST_DATA, "extract-tmp");

const { parseSummary } = __internals;

/* ============================== unit: page specs ============================== */

test("S06 adapter: parsePagesSpec handles ranges/lists and rejects junk", () => {
  assert.deepEqual(parsePagesSpec("45"), [45]);
  assert.deepEqual(parsePagesSpec("3-6,10"), [3, 4, 5, 6, 10]);
  assert.deepEqual(parsePagesSpec("33-41,155,157,159").slice(0, 3), [33, 34, 35]);
  assert.equal(parsePagesSpec("33-41,155,157,159").length, 12);
  assert.throws(() => parsePagesSpec("x"), PdfAdapterError);
  assert.throws(() => parsePagesSpec("41-33"), PdfAdapterError);
  assert.throws(() => parsePagesSpec("0"), PdfAdapterError);
  assert.throws(() => parsePagesSpec(""), PdfAdapterError);
});

test("S06 adapter: normalizePagesSpec accepts arrays and validated strings", () => {
  assert.equal(normalizePagesSpec([45, 46]), "45,46");
  assert.equal(normalizePagesSpec("33-41"), "33-41");
  assert.throws(() => normalizePagesSpec([]), PdfAdapterError);
  assert.throws(() => normalizePagesSpec([0]), PdfAdapterError);
  assert.throws(() => normalizePagesSpec([1.5]), PdfAdapterError);
  assert.throws(() => normalizePagesSpec(45), PdfAdapterError);
});

/* ============================== unit: doc validation ============================== */

function goodDoc() {
  return {
    tool: "pdf_extract",
    version: 1,
    pdf: { path: "C:/x/book_1.pdf", sha256: "a".repeat(64), pages: null },
    pages: [
      {
        file_page: 45,
        printed_page: 39,
        text_layer: true,
        lines: [[{ y: 10, text: "Questions 40-41", x0: 1, x1: 2 }]],
        figures: [{ kind: "drawing", bbox: [0, 0, 10, 10] }],
        numbers: [{ token: "40", n: 40, paren: false, x: 1, y: 2 }],
      },
    ],
  };
}

test("S06 adapter: validateExtractDoc accepts a good doc and reports missing pages", () => {
  const r = validateExtractDoc(goodDoc(), { requestedPages: [45, 46] });
  assert.equal(r.sha256, "a".repeat(64));
  assert.deepEqual(r.pages, [45]);
  assert.deepEqual(r.missingPages, [46]);
  const r2 = validateExtractDoc(goodDoc());
  assert.deepEqual(r2.missingPages, []);
});

test("S06 adapter: validateExtractDoc rejects malformed docs", () => {
  const badTool = goodDoc();
  badTool.tool = "other";
  assert.throws(() => validateExtractDoc(badTool), /tool != pdf_extract/);

  const badSha = goodDoc();
  badSha.pdf.sha256 = "zz";
  assert.throws(() => validateExtractDoc(badSha), /sha256/);

  const emptyPages = goodDoc();
  emptyPages.pages = [];
  assert.throws(() => validateExtractDoc(emptyPages), /pages missing or empty/);

  const dup = goodDoc();
  dup.pages.push({ ...dup.pages[0] });
  assert.throws(() => validateExtractDoc(dup), /duplicate page 45/);

  const badLines = goodDoc();
  badLines.pages[0].lines = "nope";
  assert.throws(() => validateExtractDoc(badLines), /lines is not an array/);

  const badOcr = goodDoc();
  badOcr.pages[0].ocr = { words: [], lines: "nope" };
  assert.throws(() => validateExtractDoc(badOcr), /ocr block malformed/);

  assert.throws(() => validateExtractDoc(null), /not an object/);
});

test("S06 adapter: parseSummary picks the last ok-json line and ignores junk", () => {
  assert.equal(parseSummary(""), null);
  assert.equal(parseSummary("hello\nworld"), null);
  const s = parseSummary('progress...\n{"ok": true, "pages": []}\n');
  assert.equal(s.ok, true);
  assert.equal(parseSummary('{"ok": false}\n{"not":"summary"}').ok, false);
});

test("S06 adapter: sha256FileHex matches a known vector", () => {
  const p = path.join(TEST_DATA, "sha-vector.txt");
  fs.mkdirSync(TEST_DATA, { recursive: true });
  fs.writeFileSync(p, "abc", "utf8");
  assert.equal(sha256FileHex(p), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
});

/* ============================== offline: import-pdf ============================== */

test("S06 import-pdf: extract-json mode writes derived + raw + provenance (offline)", () => {
  const dataDir = path.join(TEST_DATA, "import-offline");
  fs.rmSync(dataDir, { recursive: true, force: true });
  const src = path.join(TEST_DATA, "offline-extract.json");
  fs.mkdirSync(TEST_DATA, { recursive: true });
  fs.writeFileSync(src, JSON.stringify(goodDoc(), null, 1), "utf8");

  const res = importPdf({ extractJson: src, book: 1, pages: [45], dataDir, runId: "test-s06-run" });
  assert.ok(fs.existsSync(res.extractOut), "derived extract copy exists");
  assert.ok(fs.existsSync(res.provenancePath), "provenance exists");
  assert.ok(res.evidencePath && fs.existsSync(res.evidencePath), "run evidence copy exists");

  const prov = JSON.parse(fs.readFileSync(res.provenancePath, "utf8"));
  assert.equal(prov.book, "book1");
  assert.equal(prov.pdf.sha256, "a".repeat(64));
  assert.deepEqual(prov.pages, [45]);
  assert.equal(prov.tool, "pdf_extract");
  assert.equal(prov.extract.raw_sha256, res.rawSha256);

  const rawBody = path.join(res.root, prov.extract.raw_body);
  assert.ok(fs.existsSync(rawBody), "content-addressed raw body exists");
  const meta = JSON.parse(fs.readFileSync(rawBody.replace(/\.body$/, ".meta.json"), "utf8"));
  assert.equal(meta.pdf_sha256, "a".repeat(64));
  assert.deepEqual(meta.pages, [45]);

  const agg = JSON.parse(fs.readFileSync(path.join(res.root, "manifests", "pdf-provenance.json"), "utf8"));
  assert.equal(agg.entries.length, 1);
  assert.equal(agg.entries[0].pdf.sha256, "a".repeat(64));
});

/* ============================== integration: real PDFs ============================== */

function haveRealInputs() {
  if (!fs.existsSync(resolvePython())) return false;
  return fs.existsSync(path.join(DOWNLOADS, "book_1.pdf")) || fs.existsSync(path.join(DOWNLOADS, "book_3.pdf"));
}

function loadFixtures() {
  return fs
    .readdirSync(FIXTURES)
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => ({ file: f, ...JSON.parse(fs.readFileSync(path.join(FIXTURES, f), "utf8")) }));
}

const norm = (s) => String(s).replace(/\s+/g, " ").trim();
const compact = (s) => String(s).replace(/\s+/g, "");

function pageText(page) {
  return page.lines.flat().map((l) => l.text).join("\n");
}

function applyCheck(check, pages) {
  const page = pages.get(check.page);
  if (!page) return `page ${check.page} not in extraction`;
  switch (check.kind) {
    case "page_text_contains":
      if (!norm(pageText(page)).includes(norm(check.text))) {
        return `page ${check.page} text does not contain ${JSON.stringify(check.text)}`;
      }
      return null;
    case "page_text_compact_contains":
      if (!compact(pageText(page)).includes(compact(check.text))) {
        return `page ${check.page} compact text does not contain ${JSON.stringify(check.text)}`;
      }
      return null;
    case "page_line_equals":
      if (!page.lines.flat().some((l) => norm(l.text) === norm(check.text))) {
        return `page ${check.page} has no line equal to ${JSON.stringify(check.text)}`;
      }
      return null;
    case "page_numbers_include": {
      const nums = new Set((page.numbers || []).map((n) => n.n));
      for (const n of check.numbers) {
        if (!nums.has(n)) return `page ${check.page} numbers missing ${n}`;
      }
      return null;
    }
    case "page_figures_min":
      if ((page.figures || []).length < check.min) {
        return `page ${check.page} figures ${(page.figures || []).length} < ${check.min}`;
      }
      return null;
    case "page_assets_min": {
      const assets = (page.figures || []).filter((f) => f.asset).length;
      if (assets < check.min) return `page ${check.page} rendered assets ${assets} < ${check.min}`;
      return null;
    }
    case "page_text_layer":
      if (page.text_layer !== check.value) return `page ${check.page} text_layer != ${check.value}`;
      return null;
    case "page_ocr_engine":
      if (!page.ocr || page.ocr.engine !== check.engine) {
        return `page ${check.page} ocr.engine != ${check.engine}`;
      }
      return null;
    case "page_ocr_lines_contains":
      if (!page.ocr || !page.ocr.lines.some((l) => norm(l.text).includes(norm(check.text)))) {
        return `page ${check.page} ocr lines do not contain ${JSON.stringify(check.text)}`;
      }
      return null;
    case "page_ocr_compact_contains":
      if (!page.ocr || !compact(page.ocr.lines.map((l) => l.text).join("\n")).includes(compact(check.text))) {
        return `page ${check.page} ocr compact text does not contain ${JSON.stringify(check.text)}`;
      }
      return null;
    default:
      return `unknown check kind: ${check.kind}`;
  }
}

test("S06 pdf-extract: gold fixtures against real PDFs (skipped without python/PDFs)", async (t) => {
  if (!haveRealInputs()) {
    t.skip("examdata venv python or local book PDFs not present");
    return;
  }
  fs.rmSync(TMP_OUT, { recursive: true, force: true });
  fs.mkdirSync(TMP_OUT, { recursive: true });

  const fixtures = loadFixtures();
  assert.ok(fixtures.length >= 4, `expected >= 4 fixtures, found ${fixtures.length}`);

  const cache = new Map();
  for (const fx of fixtures) {
    const pdfPath = path.join(DOWNLOADS, fx.pdf);
    if (!fs.existsSync(pdfPath)) {
      t.diagnostic(`skip ${fx.case}: missing ${pdfPath}`);
      continue;
    }
    const ocrPath = fx.ocr_json ? path.join(REPO, fx.ocr_json) : null;
    if (ocrPath && !fs.existsSync(ocrPath)) {
      t.diagnostic(`skip ${fx.case}: missing ${ocrPath}`);
      continue;
    }
    const key = `${fx.pdf}|${fx.pages.join(",")}|${ocrPath || ""}`;
    let extraction = cache.get(key);
    if (!extraction) {
      const assetsDir = path.join(TMP_OUT, `${path.basename(fx.pdf, ".pdf")}-${fx.pages[0]}-assets`);
      extraction = extractPdf({
        pdf: pdfPath,
        pages: fx.pages,
        ocrJson: ocrPath || undefined,
        assets: assetsDir,
        out: path.join(TMP_OUT, `${path.basename(fx.pdf, ".pdf")}-${fx.pages[0]}.json`),
      });
      cache.set(key, extraction);
    }
    assert.equal(extraction.sha256, fx.pdf_sha256, `${fx.case}: pdf sha256`);
    assert.deepEqual(extraction.missingPages, [], `${fx.case}: no missing pages`);
    const pages = new Map(extraction.doc.pages.map((p) => [p.file_page, p]));
    for (const check of fx.checks) {
      const problem = applyCheck(check, pages);
      assert.equal(problem, null, `${fx.case}: ${problem}`);
    }
  }
});

test("S06 import-pdf: real extraction records missing pages and assets (skipped without inputs)", async (t) => {
  if (!haveRealInputs()) {
    t.skip("examdata venv python or local book PDFs not present");
    return;
  }
  const pdfPath = path.join(DOWNLOADS, "book_3.pdf");
  if (!fs.existsSync(pdfPath)) {
    t.skip("book_3.pdf not present");
    return;
  }
  const dataDir = path.join(TEST_DATA, "import-real");
  fs.rmSync(dataDir, { recursive: true, force: true });
  const assetsDir = path.join(TEST_DATA, "import-real-assets");
  fs.rmSync(assetsDir, { recursive: true, force: true });

  const res = importPdf({
    pdf: pdfPath,
    book: 3,
    pages: "37,999",
    assetsDir,
    dataDir,
    runId: "test-s06-run",
  });
  assert.deepEqual(res.missingPages, [999], "out-of-range page recorded, not silently dropped");
  assert.deepEqual(res.pages, [37]);
  assert.ok(res.assets.length >= 1, "page 37 figure asset imported");
  const prov = JSON.parse(fs.readFileSync(res.provenancePath, "utf8"));
  assert.equal(prov.pdf.sha256, "da273b47cbfa1fe324b2f289374bcfdbc7276a763e216be4f86ae6a070f06845");
  assert.deepEqual(prov.missing_pages, [999]);
  for (const a of prov.assets) {
    assert.ok(fs.existsSync(path.join(res.root, a.stored)), `asset stored: ${a.stored}`);
    assert.ok(fs.existsSync(path.join(res.root, a.derived)), `asset derived: ${a.derived}`);
  }
});
